apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kube-prometheus-stack
releaseName: kube-prometheus-stack
name: kube-prometheus-stack
version: 39.8.0
# comment if local
repo: https://prometheus-community.github.io/helm-charts
# If chart is local, set relative path FROM the /kustomize kustomization.yaml whose generator references a directory /helm
# chartHome: ../../../charts
valuesInline:
  nodeExporter:
    #  tolerations:
    #    - key: "infra"
    #      operator: "Equal"
    #      value: "tainted"
    #      effect: "NoSchedule"
    enabled: true
  #
  #kube-state-metrics:
  #  nodeSelector:
  #    workload: infra
  #  affinity:
  #    nodeAffinity:
  #        requiredDuringSchedulingIgnoredDuringExecution:
  #          nodeSelectorTerms:
  #          - matchExpressions:
  #              - key: workload
  #                operator: In
  #                values:
  #                - infra
  #  tolerations:
  #  - key: "infra"
  #    operator: "Exists"
  #    effect: "NoSchedule"

  defaultRules:
    create: true
    rules:
      alertmanager: true
      etcd: false
      configReloaders: false
      general: false
      k8s: true
      kubeApiserverAvailability: false
      kubeApiserverBurnrate: false
      kubeApiserverHistogram: false
      kubeApiserverSlos: false
      kubeControllerManager: false
      kubelet: true
      kubeProxy: false
      kubePrometheusGeneral: false
      kubePrometheusNodeRecording: false
      kubernetesApps: true
      kubernetesResources: true
      kubernetesStorage: true
      kubernetesSystem: false
      kubeScheduler: false
      kubeStateMetrics: false
      network: true
      node: true
      nodeExporterAlerting: true
      nodeExporterRecording: true
      prometheus: true
      prometheusOperator: true

  prometheusOperator:
    kubeletService:
      name: "kube-prometheus-stack-kubelet"

  grafana:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Thanos
            type: prometheus
            url: http://thanos-query.monitoring:9090
          - name: Prometheus
            type: prometheus
            uid: prometheus
            url: http://kube-prometheus-stack-prometheus.monitoring:9090/
            access: proxy
            jsonData:
              timeInterval: 30s
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 650Mi

  alertmanager:
    secret:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
  #  alertmanagerSpec:
  #    nodeSelector:
  #      workload: infra
  #    tolerations:
  #      - key: "infra"
  #        operator: "Exists"
  #        effect: "NoSchedule"
  #    affinity:
  #      nodeAffinity:
  #        requiredDuringSchedulingIgnoredDuringExecution:
  #          nodeSelectorTerms:
  #          - matchExpressions:
  #              - key: workload
  #                operator: In
  #                values:
  #                - infra

  prometheus:
    #  serviceAccount:
    #    annotations:
    #      eks.amazonaws.com/role-arn: arn:aws:iam::342376666950:role/thanos
    prometheusSpec:
      replicas: 3
      retention: 24h
      thanos:
        baseImage: quay.io/thanos/thanos
        version: v0.27.0
        objectStorageConfig:
          key: thanos-storage-config.yaml
          name: thanos-sidecar-storage-config
      #    nodeSelector:
      #      workload: infra
      #    tolerations:
      #      - key: "infra"
      #        operator: "Exists"
      #        effect: "NoSchedule"
      #    affinity:
      #      nodeAffinity:
      #        requiredDuringSchedulingIgnoredDuringExecution:
      #          nodeSelectorTerms:
      #          - matchExpressions:
      #              - key: workload
      #                operator: In
      #                values:
      #                - infra
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 20Gi
      resources:
        requests:
          cpu: 512m
          memory: 1572Mi
        limits:
          cpu: 512m
          memory: 2096Mi



